#!/bin/bash
set -e

function test_formula() {
  RESULT=`echo "$1" | bc`

  if [ $? -ne 0 ]; then
    return 1
  elif [ -z "$RESULT" ]; then
    return 1
  elif [ "$RESULT" == "1" ]; then
    return 0
  else
    return 1
  fi
}

function get_current_price() {
  MEMCACHED_KEY=`echo "$PRODUCT_DESCRIPTION;$AVAILABILITY_ZONE;$INSTANCE_TYPE" | sed 's|[ /()]|_|g'`
  memcat -s "${MEMCACHED_SERVERS:-127.0.0.1}" "$MEMCACHED_KEY"
}

CNF_FILE=$1

if [ ! -e "$CNF_FILE" ]; then
  echo 'Cannot find config file'
  exit 1
fi

. $CNF_FILE

if [ -z "$MAX_PRICE" ]; then
  echo "Please define MAX_PRICE in $CNF_FILE"
  exit 1
elif [[ ! "$MAX_PRICE" =~ ^[.0-9]+$ ]]; then
  echo "Illegal max price: $MAX_PRICE"
  exit 1
fi

if [ -z "$ON_TERMINATE" ]; then
  echo "Please define ON_TERMINATE in $CNF_FILE"
  exit 1
fi

if [ -z "$INSTANCE_TYPE" ]; then
  echo "Please define INSTANCE_TYPE in $CNF_FILE"
  exit 1
fi

if [ -z "$AVAILABILITY_ZONE" ]; then
  echo "Please define AVAILABILITY_ZONE in $CNF_FILE"
  exit 1
fi

if [ -z "$PRODUCT_DESCRIPTION" ]; then
  echo "Please define PRODUCT_DESCRIPTION in $CNF_FILE"
  exit 1
fi

if [ -z "$EXECUTE_ONCE" ]; then
  EXECUTE_ONCE=1
fi

if [ -z "$EXEC_FLAG_FILE" ]; then
  EXEC_FLAG_FILE=/var/tmp/autognosis.executed
fi

if [ "$EXECUTE_ONCE" != "0" -a -e "$EXEC_FLAG_FILE" ]; then
  exit 0
fi

CURRENT_PRICE=`get_current_price`

if [ -z "$CURRENT_PRICE" ]; then
  echo 'Cannot get curent price'
  exit 1
elif [[ ! "$CURRENT_PRICE" =~ ^[.0-9]+$ ]]; then
  echo "Illegal current price: $CURRENT_PRICE"
  exit 1
fi

test_formula "$CURRENT_PRICE > $MAX_PRICE"

if [ $? -eq 0 ]; then
  echo "Current Price exceeded Max Price: $CURRENT_PRICE > $MAX_PRICE"
  echo "Termination processing is performed: $ON_TERMINATE"

  bash -c "$ON_TERMINATE"

  if [ "$EXECUTE_ONCE" != "0" ]; then
    touch $EXEC_FLAG_FILE
  fi
fi
