#!/bin/bash
# chkconfig: - 64 36
set -e

CRONEXEC=/usr/bin/cronexec
COMMAND=/usr/sbin/autognosis
CNF_FILE=/etc/sysconfig/autognosis
PID_FILE=/var/run/autognosis.pid
LOCK_FILE=/var/lock/subsys/autognosis

if [ ! -e "$CNF_FILE" ]; then
  echo "Cannot find $CNF_FILE"
  exit 1
fi

. $CNF_FILE

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo "Please write AWS_ACCESS_KEY_ID to $CNF_FILE."
  exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "Please write AWS_SECRET_ACCESS_KEY to $CNF_FILE."
  exit 1
fi

if [ -z "$MAX_PRICE" ]; then
  echo "Please write MAX_PRICE to $CNF_FILE."
  exit 1
fi

if [ -z "$ON_TERMINATE" ]; then
  echo "Please write ON_TERMINATE to $CNF_FILE."
  exit 1
fi

if [ -z "$CHECK_INTERVAL" ]; then
  CHECK_INTERVAL=5
fi

CRONEXEC_ARGS="-W $CHECK_INTERVAL"

start()
{
  if [ -e $PID_FILE ]; then
    echo "$PID_FILE exists"
    exit 1
  fi

  [ -d "`dirname $LOCK_FILE`" ] && touch $LOCK_FILE

  nohup $CRONEXEC -W $CHECK_INTERVAL \
    -- /bin/bash -c "$BASH_ARG $COMMAND $CNF_FILE 2>&1 | logger -t autognosis" \
    > /dev/null 2> /dev/null &

  echo $! > $PID_FILE
}

stop()
{
  if [ ! -e $PID_FILE ]; then
    echo "Cannot find $PID_FILE"
    exit 1
  fi
  
  kill `cat $PID_FILE`
  rm -f $PID_FILE

  [ -d "`dirname $LOCK_FILE`" ] && rm -f $LOCK_FILE
}

restart()
{
  stop
  start
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
restart)
  restart
  ;;  
*)
  echo "Usage: $0 {start|stop|restart}"
  ;;  
esac

exit 0
