#!/bin/bash
set -e

CNF_FILE=$1

if [ ! -e "$CNF_FILE" ]; then
  echo 'Cannot find config file'
  exit 1
fi

. $CNF_FILE

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo "Please write AWS_ACCESS_KEY_ID to $CNF_FILE."
  exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "Please write AWS_SECRET_ACCESS_KEY to $CNF_FILE."
  exit 1
fi

if [ -z "$MAX_PRICE" ]; then
  echo "Please write MAX_PRICE to $CNF_FILE."
  exit 1
elif [[ ! "$MAX_PRICE" =~ ^[.0-9]+$ ]]; then
  echo "Illegal max price: $MAX_PRICE"
  exit 1
fi

if [ -z "$ON_TERMINATE" ]; then
  echo "Please write ON_TERMINATE to $CNF_FILE."
  exit 1
fi

if [ -z "$CHECK_INTERVAL" ]; then
  CHECK_INTERVAL=5
fi

if [ -z "$EXECUTE_ONCE" ]; then
  EXECUTE_ONCE=1
fi

if [ -z "$EXEC_FLAG_FILE" ]; then
  EXEC_FLAG_FILE=/var/tmp/autognosis.executed
fi

if [ "$EXECUTE_ONCE" != "0" -a -e "$EXEC_FLAG_FILE" ]; then
  exit 0
fi

if [ -z "$CURRENT_PRICE_SCRIPT" ]; then
  CURRENT_PRICE_SCRIPT='describe-spot-price-history -k "$AWS_ACCESS_KEY_ID" -s "$AWS_SECRET_ACCESS_KEY" -r "$REGION" -t "$INSTANCE_TYPE" -d Linux/UNIX -z "$AVAILABILITY_ZONE" --start-time `date -u -d "3 hours ago" +%Y-%m-%dT%H:%M:%SZ` --sort time --attrs price --tail 1 --tsv'
fi

function ec2_metadata {
  wget -q -O- http://169.254.169.254/latest/$1
}

function query_json {
  cat - | jq "$1" | sed -r 's|^"(.*)"$|\1|'
}

function fetch_map {
  echo "$1" | query_json ".$2"
}

function test_formula {
  RESULT=`echo "$1" | bc`

  if [ $? -ne 0 ]; then
    return 1
  elif [ -z "$RESULT" ]; then
    return 1
  elif [ "$RESULT" == "1" ]; then
    return 0
  else
    return 1
  fi
}

INSTANCE_IDENTITY=`ec2_metadata dynamic/instance-identity/document`

    INSTANCE_TYPE=`fetch_map "$INSTANCE_IDENTITY" instanceType`
AVAILABILITY_ZONE=`fetch_map "$INSTANCE_IDENTITY" availabilityZone`
           REGION=`fetch_map "$INSTANCE_IDENTITY" region`

CURRENT_PRICE=`
  AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
  AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
  REGION="$REGION" \
  INSTANCE_TYPE="$INSTANCE_TYPE" \
  AVAILABILITY_ZONE="$AVAILABILITY_ZONE" \
  bash -c "$CURRENT_PRICE_SCRIPT"`

if [ -z "$CURRENT_PRICE" ]; then
  echo 'Cannot get curent price'
  exit 1
elif [[ ! "$CURRENT_PRICE" =~ ^[.0-9]+$ ]]; then
  echo "Illegal current price: $CURRENT_PRICE"
  exit 1
fi

test_formula "$CURRENT_PRICE > $MAX_PRICE"

if [ $? -eq 0 ]; then
  echo "Current Price exceeded Max Price: $CURRENT_PRICE > $MAX_PRICE"
  echo "Termination processing is performed: $ON_TERMINATE"

  bash -c "$ON_TERMINATE"

  if [ "$EXECUTE_ONCE" != "0" ]; then
    touch $EXEC_FLAG_FILE
  fi
fi
